added CSS and getting the tab url
Alokit-Innovations/chrome-extension pull request #2
Opened 2023-03-04 11:46 UTC by ajayVibinex

2023-03-07 07:42 UTC, avikalpg requested changes

2023-03-07 07:42 UTC, avikalpg commented on main.js
> +console.log('This is the url',url)
Remove unnecessary logs.

2023-03-07 07:42 UTC, avikalpg commented on main.js
> +
This function is not used in your code anywhere. It can be removed.

2023-03-07 07:42 UTC, avikalpg commented on main.js
> +  one = document.head.appendChild(document.createElement("style"));
Please use a more descriptive variable name.

2023-03-07 07:42 UTC, avikalpg commented on main.js
> +  one = document.head.appendChild(document.createElement("style"));
Please use a declaration, preferably `const`.

2023-03-07 07:42 UTC, avikalpg commented on main.js
> +]
Change the mock data to mimic the contract established with the backend.
Link: [Issue 47](https://github.com/Alokit-Innovations/devprofiler-cloudrun/issues/47)

2023-03-10 11:19 UTC, ajayVibinex commented on main.js
> +    padding-bottom: 2px;;}`;
remove the extra semicolon

2023-03-10 11:20 UTC, ajayVibinex commented on main.js
> +};
Don't make two separate functions for a very similar task. Just take the "level" as parameter in the same function and modify the colors and content of the CSS accordingly.

2023-03-10 11:23 UTC, ajayVibinex commented on main.js
> +});
You don't need to write the same thing 2 times. Just make it a for loop over all the possible "level"s.
If needed, you can create an enum for levels.

2023-03-10 11:24 UTC, ajayVibinex commented on main.js
> +const output = [
use a better name than `output`. 
For example: `highlighted_PR_ids`

2023-03-10 11:25 UTC, ajayVibinex commented on manifest.json
> +        "matches":["https://github.com/*pull*","https://github.com/*pulls*"],
check if  it work only for github.com/pulls or /pull

2023-03-10 18:20 UTC, avikalpg commented
@ajayVibinex Please send me a message on Slack or Whatsapp when you fix the changes needed in this pull request.

2023-03-11 07:59 UTC, tapishr commented on main.js
> +    content: '${status}';
Delete this

2023-03-11 08:01 UTC, tapishr approved these changes

2023-03-11 08:02 UTC, merged