Github hunk level highlight
Alokit-Innovations/chrome-extension pull request #52
Opened 2023-05-12 11:17 UTC by tapishr

- [x] end-to-end tested for github

2023-05-12 11:54 UTC, ajayVibinex approved these changes

2023-05-13 10:50 UTC, avikalpg commented on scripts/contentScript.js
> +	// Todo : optomization needed to not highlight next deleted line space if not present in response.
```suggestion
	// TODO: optimization needed to not highlight next deleted line space if not present in response.
```

2023-05-13 11:00 UTC, avikalpg commented on scripts/contentScript.js
> +	let getFileName = Array.from(document.querySelectorAll('div[data-tagsearch-path]'));
```suggestion
	const getFileName = Array.from(document.querySelectorAll('div[data-tagsearch-path]'));
```

Use `const` wherever possible. `let` signifies that you want to modify this value somewhere down the line.

2023-05-13 11:11 UTC, avikalpg requested changes

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +		let FileContent = item.getAttribute('data-tagsearch-path');
```suggestion
		const fileContent = item.getAttribute('data-tagsearch-path');
```

1. use `const` wherever possible
2. We use camelCase for normal variables. PascalCase is used for classes, singletons etc.

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +							let tableContent = items.querySelector("td[data-split-side='left']");
Please use `const` wherever possible. It is not a good practice to use `let`. I don't think any of these variables are being reassigned (except `foundFile`). Using `let` just makes the code less readable.

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +					foundFile = item;
Shouldn't we `break` after finding the file? If not, is it possible to find another item that matches this? If yes, then what happens to the previously found item?

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +		const fileName = ariaLabel.substring(13);
Low LOGAF:
Why do we need to hardcode this number? Is this the best way to handle this?

```suggestion
		const fileName = ariaLabel.substring("Diff of file".length);
```

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +		let foundFile = apiResponses.some(item => item.filepath === matchEncrypted);
`const` instead of `let`

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +			for (k in apiResponses["hunkinfo"]) {
You have used the `.some` operation in the bitbucket function. Maybe you can use the same here for the `foundFile` variable?

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +			const linesWrappe = article.querySelectorAll('.lines-wrapper');
```suggestion
			const linesWrapper = article.querySelectorAll('.lines-wrapper');
```

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +				const FromLineElements = item.querySelectorAll('a[aria-label^="From line"]');
camelCase instead of PascalCase

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +					const lineNumber = ariaLabel.substring(8);
Isn't there a better, more readable way to handle this instead of hardcoding `8`?

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +					console.log(lineNumber);
Can we remove this `console.log`?

2023-05-13 11:11 UTC, avikalpg commented on scripts/contentScript.js
> +					console.log(lineNumber);
Hardcoded `8` and console.log.

2023-05-15 06:23 UTC, merged